<?php

namespace Src\ChainOfResponsibility\Loan\Verifier;

use Src\ChainOfResponsibility\Loan\LoanRequest;
use Src\ChainOfResponsibility\Loan\LoanVerifier;
use Src\ChainOfResponsibility\Loan\Models\User;

class LoanAmountVerifier extends LoanVerifier
{
   public function verify(LoanRequest $request): bool
   {
       if (!$this->checkAmountIsValid($request->getAmount()))
           return false;
       return parent::verify($request); // TODO: Change the autogenerated stub
   }

    private function checkAmountIsValid(mixed $amount) :bool
    {
        return $amount < 20000000;
    }
}
