<?php

namespace Src\ChainOfResponsibility\Loan\Verifier;

use Src\ChainOfResponsibility\Loan\LoanRequest;
use Src\ChainOfResponsibility\Loan\LoanVerifier;
use Src\ChainOfResponsibility\Loan\Models\User;

class UserCanGetLoanVerifier extends LoanVerifier
{

    public function verify(LoanRequest $request): bool
    {
        if (! $this->userCanGetLoan($request->getUserId()))
            return false;
        return parent::verify($request); // TODO: Change the autogenerated stub
    }

    private function userCanGetLoan(mixed $userID):bool
    {
        $user = User::find($userID);
        return $user->userCanGetLoan();
    }

}
