<?php

namespace Src\ChainOfResponsibility\AccessProduct\Verifiers;

use Src\ChainOfResponsibility\AccessProduct\Models\Product;
use Src\ChainOfResponsibility\AccessProduct\Models\User;
use Src\ChainOfResponsibility\AccessProduct\Verifier;

class ActiveUserVerifier extends Verifier
{
    public function verify(User $user, Product $product): bool
    {
        if (!$user->isActive())
            return false;
        return parent::verify($user, $product); // TODO: Change the autogenerated stub
    }
}
