<?php

namespace Src\ChainOfResponsibility\AccessProduct\Verifiers;

use Src\ChainOfResponsibility\AccessProduct\Models\Product;
use Src\ChainOfResponsibility\AccessProduct\Models\Subscription;
use Src\ChainOfResponsibility\AccessProduct\Models\User;
use Src\ChainOfResponsibility\AccessProduct\Verifier;

class ExpirationSubscriptionVerifier extends Verifier
{
    public function verify(User $user, Product $product): bool
    {
        $s = Subscription::findByUserIDAndProductID($user->id, $product->id);
        if ($s->checkIsExpired())
            return false;
        return parent::verify($user, $product); // TODO: Change the autogenerated stub
    }
}
