<?php

namespace Src\ChainOfResponsibility\AccessProduct\Verifiers;

use Src\ChainOfResponsibility\AccessProduct\Models\Product;
use Src\ChainOfResponsibility\AccessProduct\Models\Subscription;
use Src\ChainOfResponsibility\AccessProduct\Models\User;
use Src\ChainOfResponsibility\AccessProduct\Verifier;

class SubscriptionVerifier extends Verifier
{
    public function verify(User $user, Product $product): bool
    {
        if (!Subscription::findByUserIDAndProductID($user->id, $product->id))
            return false;
        return parent::verify($user, $product); // TODO: Change the autogenerated stub
    }
}
